#cloud-config

coreos:
    units:
      - name: media-configdrive.mount
        command: start
        runtime: yes
        content: |
          [Unit]
          Wants=user-configdrive.service
          Before=user-configdrive.service
          [Mount]
          What=/dev/disk/by-label/config-2
          Where=/media/configdrive
          Options=ro
    oem:
      id: baremetal
      name: Bare Metal Servers with Config-Drive
      version-id: 1
      home-url: https://keep.com/
      bug-report-url: https://github.com/coreos/coreos-overlay
write_files:
    - path: /run/systemd/system/etcd.service.d/10-oem.conf
      permissions: 0644
      content: |
        [Service]
        Environment=ETCD_PEER_ELECTION_TIMEOUT=1200